### ISSUE TITLE
/usr/bin/env: ‘node’: No such file or directory

### ISSUE THREAD

**Issue by jamieduk** [RobertCorey/five-oh-poker-bot#1]
I get error

nodemon server.js
/usr/bin/env: ‘node’: No such file or directory
when i add a sym link for the thing and re run i get this error

nodemon server.js
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
module.js:328
    throw err;
    ^

Error: Cannot find module 'poker-evaluator'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/html/apps/games/poker/mp/server/logic.js:1:84)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by RobertCorey** [comment]
Hey Jamie, this bot depends on this library https://github.com/chenosaurus/poker-evaluator . which looks like isn't being installed. I remember having issues with it because it's a big library and it's over the size limit. email me @ robertbcorey@gmail.com if you want to set up a call to help you get it working or if you just want to talk bots (: .
